#!/bin/sh

GOPATH=/users/gford1000/Go

protoc -I=/usr/local/include --go_out=$GOPATH/src --proto_path=. algo.proto

protoc -I=/usr/local/include --go_out=$GOPATH/src --proto_path=. encrypted_object.proto

protoc -I=/usr/local/include --go_out=$GOPATH/src --proto_path=. keys.proto
