#!/bin/sh

GOPATH=/users/gford1000/Go

protoc -I=/usr/local/include -I=$GOPATH/src/github.com/gford1000-go/protobuf/types/value -I=$GOPATH/src/github.com/gford1000-go/protobuf/types/encrypted_value -I=$GOPATH/src/github.com/gford1000-go/protobuf/types/encryption --go_out=$GOPATH/src --proto_path=. encryptable_value.proto
